#!/usr/bin/python3
"""
Module Name: base

Module Description:
This module contains only one Class

Module Classes:
- Base

Module Attributes:
- None
"""


class Base:
    """
    The Base class is a simple class for generating unique IDs.

    Attributes:
        __nb_objects (int): A class variable that keeps track of
                            the number of objects created.

    Methods:
        __init__(self, id=None): Initializes a new instance of
                                 the Base class with a unique ID.
    """

    __nb_objects = 0

    def __init__(self, id=None):
        """
        Initializes a new instance of the Base class with a unique ID.

        Args:
            id (int, optional): An optional ID that can be assigned
                                to the instance. If None, the instance
                                is assigned a unique ID generated by the class.

        Returns:
            None.
        """
        if (id is not None):
            self.id = id
        else:
            Base.__nb_objects += 1
            self.id = Base.__nb_objects
