#!/usr/bin/env python3
import os
import py_compile

pyfile = os.environ.get("PYFILE")

if not pyfile:
    print("Error: PYFILE environment variable not set.")
    exit(1)

py_compile.compile(pyfile, cfile=pyfile + "c")
print("Compiling main.py ...")
